FROM node:18-alpine AS builder

WORKDIR /app/frontend

COPY package.json ./
COPY package-lock.json ./
RUN npm ci
COPY . .
COPY .env .env
RUN npm run build

FROM nginx:1.25-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/frontend/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
