services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      # pg_isready to check if the database server is accepting connections
      test: ["CMD-SHELL", "pg_isready -U user -d userdb -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  user-service:
    build:
      context: ./backend
      dockerfile: user-service/Dockerfile
    ports:
      - "50051:50051"
    env_file: ./backend/user-service/.env
    depends_on:
      postgres:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1

  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    env_file: ./backend/api-gateway/.env
    depends_on:
      - user-service

volumes:
  postgres_data:
