services:
  postgres:
    image: postgres:15
    container_name: ay-postgres-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_main_data:/var/lib/postgresql/data
      # script for creating multiple databases
      - ./scripts/init-multiple-databases.sh:/docker-entrypoint-initdb.d/init-multiple-databases.sh
    healthcheck:
      # pg_isready to check if the database server is accepting connections
      test: ["CMD-SHELL", "pg_isready -U user -d postgres -h localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 20s

  user-service:
    build:
      context: ./backend
      dockerfile: user-service/Dockerfile
    container_name: user-service
    ports:
      - "50051:50051"
    env_file: ./backend/user-service/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.default.disable_ipv6=1

  thread-service:
    build:
      context: ./backend
      dockerfile: thread-service/Dockerfile
    container_name: thread-service
    ports:
      - "50052:50052"
    env_file: ./backend/thread-service/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  media-service:
    build:
      context: ./backend
      dockerfile: media-service/Dockerfile
    container_name: media-service
    ports:
      - "50053:50053"
    env_file: ./backend/media-service/.env
    depends_on:
      postgres:
        condition: service_healthy

  search-service:
    build:
      context: ./backend
      dockerfile: search-service/Dockerfile
    container_name: search-service
    ports:
      - "50054:50054"
    env_file: ./backend/search-service/.env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  notification-service:
    build:
      context: ./backend
      dockerfile: notification-service/Dockerfile
    container_name: notification-service
    ports:
      - "50055:50055"
      - "8081:8081" # WebSocket port
    env_file: ./backend/notification-service/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
      user-service:
        condition: service_started

  message-service:
    build:
      context: ./backend
      dockerfile: message-service/Dockerfile
    container_name: message-service
    ports:
      - "50056:50056"
      - "8082:8082" # WebSocket port
    env_file: ./backend/message-service/.env
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  community-service:
    build:
      context: ./backend
      dockerfile: community-service/Dockerfile
    container_name: community-service
    ports:
      - "50057:50057"
    env_file: ./backend/community-service/.env
    depends_on:
      postgres:
        condition: service_healthy

  ai-service:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: ai-service
    ports:
      - "5000:5000"
    volumes:
      - ./ai:/app

  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile
    container_name: api-gateway
    ports:
      - "8080:8080"
    env_file: ./backend/api-gateway/.env
    depends_on:
      - user-service
      - thread-service
      - media-service
      - message-service

  redis:
    image: redis:7-alpine
    container_name: ay-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    container_name: ay-rabbitmq
    ports:
      - "5672:5672" # AMQP port
      - "15672:15672" # Management UI port
    environment:
      # Default user/pass is guest/guest
      RABBITMQ_DEFAULT_VHOST: "/"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./frontend
    container_name: ay-frontend
    ports:
      - "5173:80" # Map host port 5173 to container's Nginx port 80
    depends_on:
      - api-gateway

volumes:
  postgres_main_data:
  redis_data:
  rabbitmq_data:
