version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: userdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: ./backend
      dockerfile: user-service/Dockerfile
    ports:
      - "50051:50051"
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/userdb?sslmode=disable
    depends_on:
      - postgres

  api-gateway:
    build:
      context: ./backend
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - USER_SERVICE_ADDR=user-service:50051
    depends_on:
      - user-service

volumes:
  postgres_data:
