// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/message.proto

package messagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Chat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`       // "direct", "group"
	Name          *string                `protobuf:"bytes,3,opt,name=name,proto3,oneof" json:"name,omitempty"` // For group chats
	CreatorId     uint32                 `protobuf:"varint,4,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"` // When last message was sent
	Participants  []*UserSummary         `protobuf:"bytes,7,rep,name=participants,proto3" json:"participants,omitempty"`
	LastMessage   *Message               `protobuf:"bytes,8,opt,name=last_message,json=lastMessage,proto3,oneof" json:"last_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Chat) Reset() {
	*x = Chat{}
	mi := &file_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Chat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Chat) ProtoMessage() {}

func (x *Chat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Chat.ProtoReflect.Descriptor instead.
func (*Chat) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *Chat) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Chat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Chat) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Chat) GetCreatorId() uint32 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *Chat) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Chat) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Chat) GetParticipants() []*UserSummary {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *Chat) GetLastMessage() *Message {
	if x != nil {
		return x.LastMessage
	}
	return nil
}

type UserSummary struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name              string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Username          string                 `protobuf:"bytes,3,opt,name=username,proto3" json:"username,omitempty"`
	ProfilePictureUrl string                 `protobuf:"bytes,4,opt,name=profile_picture_url,json=profilePictureUrl,proto3" json:"profile_picture_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_proto_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{2}
}

func (x *UserSummary) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserSummary) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserSummary) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSummary) GetProfilePictureUrl() string {
	if x != nil {
		return x.ProfilePictureUrl
	}
	return ""
}

// from media.proto
type Media struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UploaderUserId uint32                 `protobuf:"varint,2,opt,name=uploader_user_id,json=uploaderUserId,proto3" json:"uploader_user_id,omitempty"`
	SupabasePath   string                 `protobuf:"bytes,3,opt,name=supabase_path,json=supabasePath,proto3" json:"supabase_path,omitempty"`
	BucketName     string                 `protobuf:"bytes,4,opt,name=bucket_name,json=bucketName,proto3" json:"bucket_name,omitempty"`
	MimeType       string                 `protobuf:"bytes,5,opt,name=mime_type,json=mimeType,proto3" json:"mime_type,omitempty"`
	FileSize       int64                  `protobuf:"varint,6,opt,name=file_size,json=fileSize,proto3" json:"file_size,omitempty"`
	PublicUrl      string                 `protobuf:"bytes,7,opt,name=public_url,json=publicUrl,proto3" json:"public_url,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Media) Reset() {
	*x = Media{}
	mi := &file_proto_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Media) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Media) ProtoMessage() {}

func (x *Media) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Media.ProtoReflect.Descriptor instead.
func (*Media) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{3}
}

func (x *Media) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Media) GetUploaderUserId() uint32 {
	if x != nil {
		return x.UploaderUserId
	}
	return 0
}

func (x *Media) GetSupabasePath() string {
	if x != nil {
		return x.SupabasePath
	}
	return ""
}

func (x *Media) GetBucketName() string {
	if x != nil {
		return x.BucketName
	}
	return ""
}

func (x *Media) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *Media) GetFileSize() int64 {
	if x != nil {
		return x.FileSize
	}
	return 0
}

func (x *Media) GetPublicUrl() string {
	if x != nil {
		return x.PublicUrl
	}
	return ""
}

func (x *Media) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ChatId        uint32                 `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      uint32                 `protobuf:"varint,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Type          string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`                                 // "text", "image", etc.
	MediaIds      []uint32               `protobuf:"varint,6,rep,packed,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"` // IDs from Media Service
	MediaItems    []*Media               `protobuf:"bytes,7,rep,name=media_items,json=mediaItems,proto3" json:"media_items,omitempty"`   // Alternative: send hydrated media
	SentAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`
	IsDeleted     bool                   `protobuf:"varint,9,opt,name=is_deleted,json=isDeleted,proto3" json:"is_deleted,omitempty"`
	SenderSummary *UserSummary           `protobuf:"bytes,10,opt,name=sender_summary,json=senderSummary,proto3" json:"sender_summary,omitempty"` // Hydrated sender info
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_proto_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{4}
}

func (x *Message) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Message) GetChatId() uint32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *Message) GetSenderId() uint32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Message) GetMediaIds() []uint32 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

func (x *Message) GetMediaItems() []*Media {
	if x != nil {
		return x.MediaItems
	}
	return nil
}

func (x *Message) GetSentAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SentAt
	}
	return nil
}

func (x *Message) GetIsDeleted() bool {
	if x != nil {
		return x.IsDeleted
	}
	return false
}

func (x *Message) GetSenderSummary() *UserSummary {
	if x != nil {
		return x.SenderSummary
	}
	return nil
}

type GetOrCreateDirectChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId1       uint32                 `protobuf:"varint,1,opt,name=user_id1,json=userId1,proto3" json:"user_id1,omitempty"` // Current authenticated user
	UserId2       uint32                 `protobuf:"varint,2,opt,name=user_id2,json=userId2,proto3" json:"user_id2,omitempty"` // The other user
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetOrCreateDirectChatRequest) Reset() {
	*x = GetOrCreateDirectChatRequest{}
	mi := &file_proto_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetOrCreateDirectChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOrCreateDirectChatRequest) ProtoMessage() {}

func (x *GetOrCreateDirectChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOrCreateDirectChatRequest.ProtoReflect.Descriptor instead.
func (*GetOrCreateDirectChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{5}
}

func (x *GetOrCreateDirectChatRequest) GetUserId1() uint32 {
	if x != nil {
		return x.UserId1
	}
	return 0
}

func (x *GetOrCreateDirectChatRequest) GetUserId2() uint32 {
	if x != nil {
		return x.UserId2
	}
	return 0
}

type SendMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint32                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	SenderId      uint32                 `protobuf:"varint,2,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	MediaIds      []uint32               `protobuf:"varint,4,rep,packed,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`
	Type          *string                `protobuf:"bytes,6,opt,name=type,proto3,oneof" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_proto_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{6}
}

func (x *SendMessageRequest) GetChatId() uint32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *SendMessageRequest) GetSenderId() uint32 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *SendMessageRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageRequest) GetMediaIds() []uint32 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

func (x *SendMessageRequest) GetType() string {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return ""
}

type GetMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint32                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesRequest) Reset() {
	*x = GetMessagesRequest{}
	mi := &file_proto_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesRequest) ProtoMessage() {}

func (x *GetMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesRequest.ProtoReflect.Descriptor instead.
func (*GetMessagesRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{7}
}

func (x *GetMessagesRequest) GetChatId() uint32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *GetMessagesRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetMessagesRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetMessagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMessagesResponse) Reset() {
	*x = GetMessagesResponse{}
	mi := &file_proto_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMessagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMessagesResponse) ProtoMessage() {}

func (x *GetMessagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMessagesResponse.ProtoReflect.Descriptor instead.
func (*GetMessagesResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{8}
}

func (x *GetMessagesResponse) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *GetMessagesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type DeleteMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     uint32                 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMessageRequest) Reset() {
	*x = DeleteMessageRequest{}
	mi := &file_proto_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMessageRequest) ProtoMessage() {}

func (x *DeleteMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMessageRequest.ProtoReflect.Descriptor instead.
func (*DeleteMessageRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteMessageRequest) GetMessageId() uint32 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *DeleteMessageRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetUserChatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserChatsRequest) Reset() {
	*x = GetUserChatsRequest{}
	mi := &file_proto_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserChatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserChatsRequest) ProtoMessage() {}

func (x *GetUserChatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserChatsRequest.ProtoReflect.Descriptor instead.
func (*GetUserChatsRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserChatsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetUserChatsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserChatsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetUserChatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chats         []*Chat                `protobuf:"bytes,1,rep,name=chats,proto3" json:"chats,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserChatsResponse) Reset() {
	*x = GetUserChatsResponse{}
	mi := &file_proto_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserChatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserChatsResponse) ProtoMessage() {}

func (x *GetUserChatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserChatsResponse.ProtoReflect.Descriptor instead.
func (*GetUserChatsResponse) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserChatsResponse) GetChats() []*Chat {
	if x != nil {
		return x.Chats
	}
	return nil
}

func (x *GetUserChatsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint32                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_proto_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{12}
}

func (x *DeleteChatRequest) GetChatId() uint32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *DeleteChatRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type CreateGroupChatRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	CreatorId             uint32                 `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	GroupName             string                 `protobuf:"bytes,2,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	InitialParticipantIds []uint32               `protobuf:"varint,3,rep,packed,name=initial_participant_ids,json=initialParticipantIds,proto3" json:"initial_participant_ids,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CreateGroupChatRequest) Reset() {
	*x = CreateGroupChatRequest{}
	mi := &file_proto_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupChatRequest) ProtoMessage() {}

func (x *CreateGroupChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupChatRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{13}
}

func (x *CreateGroupChatRequest) GetCreatorId() uint32 {
	if x != nil {
		return x.CreatorId
	}
	return 0
}

func (x *CreateGroupChatRequest) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

func (x *CreateGroupChatRequest) GetInitialParticipantIds() []uint32 {
	if x != nil {
		return x.InitialParticipantIds
	}
	return nil
}

type UpdateGroupParticipantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChatId        uint32                 `protobuf:"varint,1,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	ActorUserId   uint32                 `protobuf:"varint,2,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	TargetUserId  uint32                 `protobuf:"varint,3,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupParticipantsRequest) Reset() {
	*x = UpdateGroupParticipantsRequest{}
	mi := &file_proto_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupParticipantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupParticipantsRequest) ProtoMessage() {}

func (x *UpdateGroupParticipantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupParticipantsRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupParticipantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_message_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateGroupParticipantsRequest) GetChatId() uint32 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *UpdateGroupParticipantsRequest) GetActorUserId() uint32 {
	if x != nil {
		return x.ActorUserId
	}
	return 0
}

func (x *UpdateGroupParticipantsRequest) GetTargetUserId() uint32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

var File_proto_message_proto protoreflect.FileDescriptor

const file_proto_message_proto_rawDesc = "" +
	"\n" +
	"\x13proto/message.proto\x12\amessage\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xe6\x02\n" +
	"\x04Chat\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x17\n" +
	"\x04name\x18\x03 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x04 \x01(\rR\tcreatorId\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x128\n" +
	"\fparticipants\x18\a \x03(\v2\x14.message.UserSummaryR\fparticipants\x128\n" +
	"\flast_message\x18\b \x01(\v2\x10.message.MessageH\x01R\vlastMessage\x88\x01\x01B\a\n" +
	"\x05_nameB\x0f\n" +
	"\r_last_message\"}\n" +
	"\vUserSummary\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\busername\x18\x03 \x01(\tR\busername\x12.\n" +
	"\x13profile_picture_url\x18\x04 \x01(\tR\x11profilePictureUrl\"\x9b\x02\n" +
	"\x05Media\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12(\n" +
	"\x10uploader_user_id\x18\x02 \x01(\rR\x0euploaderUserId\x12#\n" +
	"\rsupabase_path\x18\x03 \x01(\tR\fsupabasePath\x12\x1f\n" +
	"\vbucket_name\x18\x04 \x01(\tR\n" +
	"bucketName\x12\x1b\n" +
	"\tmime_type\x18\x05 \x01(\tR\bmimeType\x12\x1b\n" +
	"\tfile_size\x18\x06 \x01(\x03R\bfileSize\x12\x1d\n" +
	"\n" +
	"public_url\x18\a \x01(\tR\tpublicUrl\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xdc\x02\n" +
	"\aMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\achat_id\x18\x02 \x01(\rR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\rR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1b\n" +
	"\tmedia_ids\x18\x06 \x03(\rR\bmediaIds\x12/\n" +
	"\vmedia_items\x18\a \x03(\v2\x0e.message.MediaR\n" +
	"mediaItems\x123\n" +
	"\asent_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06sentAt\x12\x1d\n" +
	"\n" +
	"is_deleted\x18\t \x01(\bR\tisDeleted\x12;\n" +
	"\x0esender_summary\x18\n" +
	" \x01(\v2\x14.message.UserSummaryR\rsenderSummary\"T\n" +
	"\x1cGetOrCreateDirectChatRequest\x12\x19\n" +
	"\buser_id1\x18\x01 \x01(\rR\auserId1\x12\x19\n" +
	"\buser_id2\x18\x02 \x01(\rR\auserId2\"\xa3\x01\n" +
	"\x12SendMessageRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\rR\x06chatId\x12\x1b\n" +
	"\tsender_id\x18\x02 \x01(\rR\bsenderId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x1b\n" +
	"\tmedia_ids\x18\x04 \x03(\rR\bmediaIds\x12\x17\n" +
	"\x04type\x18\x06 \x01(\tH\x00R\x04type\x88\x01\x01B\a\n" +
	"\x05_type\"p\n" +
	"\x12GetMessagesRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\rR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"^\n" +
	"\x13GetMessagesResponse\x12,\n" +
	"\bmessages\x18\x01 \x03(\v2\x10.message.MessageR\bmessages\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"N\n" +
	"\x14DeleteMessageRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\rR\tmessageId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"X\n" +
	"\x13GetUserChatsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"V\n" +
	"\x14GetUserChatsResponse\x12#\n" +
	"\x05chats\x18\x01 \x03(\v2\r.message.ChatR\x05chats\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"E\n" +
	"\x11DeleteChatRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\rR\x06chatId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"\x8e\x01\n" +
	"\x16CreateGroupChatRequest\x12\x1d\n" +
	"\n" +
	"creator_id\x18\x01 \x01(\rR\tcreatorId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x02 \x01(\tR\tgroupName\x126\n" +
	"\x17initial_participant_ids\x18\x03 \x03(\rR\x15initialParticipantIds\"\x83\x01\n" +
	"\x1eUpdateGroupParticipantsRequest\x12\x17\n" +
	"\achat_id\x18\x01 \x01(\rR\x06chatId\x12\"\n" +
	"\ractor_user_id\x18\x02 \x01(\rR\vactorUserId\x12$\n" +
	"\x0etarget_user_id\x18\x03 \x01(\rR\ftargetUserId2\xfa\x05\n" +
	"\x0eMessageService\x12>\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x17.message.HealthResponse\x12M\n" +
	"\x15GetOrCreateDirectChat\x12%.message.GetOrCreateDirectChatRequest\x1a\r.message.Chat\x12@\n" +
	"\n" +
	"DeleteChat\x12\x1a.message.DeleteChatRequest\x1a\x16.google.protobuf.Empty\x12A\n" +
	"\x0fCreateGroupChat\x12\x1f.message.CreateGroupChatRequest\x1a\r.message.Chat\x12X\n" +
	"\x15AddParticipantToGroup\x12'.message.UpdateGroupParticipantsRequest\x1a\x16.google.protobuf.Empty\x12]\n" +
	"\x1aRemoveParticipantFromGroup\x12'.message.UpdateGroupParticipantsRequest\x1a\x16.google.protobuf.Empty\x12<\n" +
	"\vSendMessage\x12\x1b.message.SendMessageRequest\x1a\x10.message.Message\x12H\n" +
	"\vGetMessages\x12\x1b.message.GetMessagesRequest\x1a\x1c.message.GetMessagesResponse\x12F\n" +
	"\rDeleteMessage\x12\x1d.message.DeleteMessageRequest\x1a\x16.google.protobuf.Empty\x12K\n" +
	"\fGetUserChats\x12\x1c.message.GetUserChatsRequest\x1a\x1d.message.GetUserChatsResponseBVZTgithub.com/Acad600-TPA/WEB-MJ-242/backend/message-service/genproto/message;messagepbb\x06proto3"

var (
	file_proto_message_proto_rawDescOnce sync.Once
	file_proto_message_proto_rawDescData []byte
)

func file_proto_message_proto_rawDescGZIP() []byte {
	file_proto_message_proto_rawDescOnce.Do(func() {
		file_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)))
	})
	return file_proto_message_proto_rawDescData
}

var file_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_proto_message_proto_goTypes = []any{
	(*HealthResponse)(nil),                 // 0: message.HealthResponse
	(*Chat)(nil),                           // 1: message.Chat
	(*UserSummary)(nil),                    // 2: message.UserSummary
	(*Media)(nil),                          // 3: message.Media
	(*Message)(nil),                        // 4: message.Message
	(*GetOrCreateDirectChatRequest)(nil),   // 5: message.GetOrCreateDirectChatRequest
	(*SendMessageRequest)(nil),             // 6: message.SendMessageRequest
	(*GetMessagesRequest)(nil),             // 7: message.GetMessagesRequest
	(*GetMessagesResponse)(nil),            // 8: message.GetMessagesResponse
	(*DeleteMessageRequest)(nil),           // 9: message.DeleteMessageRequest
	(*GetUserChatsRequest)(nil),            // 10: message.GetUserChatsRequest
	(*GetUserChatsResponse)(nil),           // 11: message.GetUserChatsResponse
	(*DeleteChatRequest)(nil),              // 12: message.DeleteChatRequest
	(*CreateGroupChatRequest)(nil),         // 13: message.CreateGroupChatRequest
	(*UpdateGroupParticipantsRequest)(nil), // 14: message.UpdateGroupParticipantsRequest
	(*timestamppb.Timestamp)(nil),          // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                  // 16: google.protobuf.Empty
}
var file_proto_message_proto_depIdxs = []int32{
	15, // 0: message.Chat.created_at:type_name -> google.protobuf.Timestamp
	15, // 1: message.Chat.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: message.Chat.participants:type_name -> message.UserSummary
	4,  // 3: message.Chat.last_message:type_name -> message.Message
	15, // 4: message.Media.created_at:type_name -> google.protobuf.Timestamp
	3,  // 5: message.Message.media_items:type_name -> message.Media
	15, // 6: message.Message.sent_at:type_name -> google.protobuf.Timestamp
	2,  // 7: message.Message.sender_summary:type_name -> message.UserSummary
	4,  // 8: message.GetMessagesResponse.messages:type_name -> message.Message
	1,  // 9: message.GetUserChatsResponse.chats:type_name -> message.Chat
	16, // 10: message.MessageService.HealthCheck:input_type -> google.protobuf.Empty
	5,  // 11: message.MessageService.GetOrCreateDirectChat:input_type -> message.GetOrCreateDirectChatRequest
	12, // 12: message.MessageService.DeleteChat:input_type -> message.DeleteChatRequest
	13, // 13: message.MessageService.CreateGroupChat:input_type -> message.CreateGroupChatRequest
	14, // 14: message.MessageService.AddParticipantToGroup:input_type -> message.UpdateGroupParticipantsRequest
	14, // 15: message.MessageService.RemoveParticipantFromGroup:input_type -> message.UpdateGroupParticipantsRequest
	6,  // 16: message.MessageService.SendMessage:input_type -> message.SendMessageRequest
	7,  // 17: message.MessageService.GetMessages:input_type -> message.GetMessagesRequest
	9,  // 18: message.MessageService.DeleteMessage:input_type -> message.DeleteMessageRequest
	10, // 19: message.MessageService.GetUserChats:input_type -> message.GetUserChatsRequest
	0,  // 20: message.MessageService.HealthCheck:output_type -> message.HealthResponse
	1,  // 21: message.MessageService.GetOrCreateDirectChat:output_type -> message.Chat
	16, // 22: message.MessageService.DeleteChat:output_type -> google.protobuf.Empty
	1,  // 23: message.MessageService.CreateGroupChat:output_type -> message.Chat
	16, // 24: message.MessageService.AddParticipantToGroup:output_type -> google.protobuf.Empty
	16, // 25: message.MessageService.RemoveParticipantFromGroup:output_type -> google.protobuf.Empty
	4,  // 26: message.MessageService.SendMessage:output_type -> message.Message
	8,  // 27: message.MessageService.GetMessages:output_type -> message.GetMessagesResponse
	16, // 28: message.MessageService.DeleteMessage:output_type -> google.protobuf.Empty
	11, // 29: message.MessageService.GetUserChats:output_type -> message.GetUserChatsResponse
	20, // [20:30] is the sub-list for method output_type
	10, // [10:20] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_message_proto_init() }
func file_proto_message_proto_init() {
	if File_proto_message_proto != nil {
		return
	}
	file_proto_message_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_message_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_message_proto_rawDesc), len(file_proto_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_message_proto_goTypes,
		DependencyIndexes: file_proto_message_proto_depIdxs,
		MessageInfos:      file_proto_message_proto_msgTypes,
	}.Build()
	File_proto_message_proto = out.File
	file_proto_message_proto_goTypes = nil
	file_proto_message_proto_depIdxs = nil
}
