// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/search.proto

package searchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserIDResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDResult) Reset() {
	*x = UserIDResult{}
	mi := &file_proto_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDResult) ProtoMessage() {}

func (x *UserIDResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDResult.ProtoReflect.Descriptor instead.
func (*UserIDResult) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{2}
}

func (x *UserIDResult) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ThreadIDResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentSnippet string                 `protobuf:"bytes,2,opt,name=content_snippet,json=contentSnippet,proto3" json:"content_snippet,omitempty"`
	UserId         uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThreadIDResult) Reset() {
	*x = ThreadIDResult{}
	mi := &file_proto_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadIDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadIDResult) ProtoMessage() {}

func (x *ThreadIDResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadIDResult.ProtoReflect.Descriptor instead.
func (*ThreadIDResult) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{3}
}

func (x *ThreadIDResult) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ThreadIDResult) GetContentSnippet() string {
	if x != nil {
		return x.ContentSnippet
	}
	return ""
}

func (x *ThreadIDResult) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SearchUserIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserResults   []*UserIDResult        `protobuf:"bytes,1,rep,name=user_results,json=userResults,proto3" json:"user_results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserIDsResponse) Reset() {
	*x = SearchUserIDsResponse{}
	mi := &file_proto_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserIDsResponse) ProtoMessage() {}

func (x *SearchUserIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserIDsResponse.ProtoReflect.Descriptor instead.
func (*SearchUserIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUserIDsResponse) GetUserResults() []*UserIDResult {
	if x != nil {
		return x.UserResults
	}
	return nil
}

func (x *SearchUserIDsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type SearchThreadIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadResults []*ThreadIDResult      `protobuf:"bytes,1,rep,name=thread_results,json=threadResults,proto3" json:"thread_results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchThreadIDsResponse) Reset() {
	*x = SearchThreadIDsResponse{}
	mi := &file_proto_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchThreadIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchThreadIDsResponse) ProtoMessage() {}

func (x *SearchThreadIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchThreadIDsResponse.ProtoReflect.Descriptor instead.
func (*SearchThreadIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchThreadIDsResponse) GetThreadResults() []*ThreadIDResult {
	if x != nil {
		return x.ThreadResults
	}
	return nil
}

func (x *SearchThreadIDsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetTrendingHashtagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingHashtagsRequest) Reset() {
	*x = GetTrendingHashtagsRequest{}
	mi := &file_proto_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingHashtagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingHashtagsRequest) ProtoMessage() {}

func (x *GetTrendingHashtagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingHashtagsRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingHashtagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{6}
}

func (x *GetTrendingHashtagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTrendingHashtagsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashtags      []string               `protobuf:"bytes,1,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingHashtagsResponse) Reset() {
	*x = GetTrendingHashtagsResponse{}
	mi := &file_proto_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingHashtagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingHashtagsResponse) ProtoMessage() {}

func (x *GetTrendingHashtagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingHashtagsResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingHashtagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{7}
}

func (x *GetTrendingHashtagsResponse) GetHashtags() []string {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

var File_proto_search_proto protoreflect.FileDescriptor

const file_proto_search_proto_rawDesc = "" +
	"\n" +
	"\x12proto/search.proto\x12\x06search\x1a\x1bgoogle/protobuf/empty.proto\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"O\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x1e\n" +
	"\fUserIDResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"b\n" +
	"\x0eThreadIDResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12'\n" +
	"\x0fcontent_snippet\x18\x02 \x01(\tR\x0econtentSnippet\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"k\n" +
	"\x15SearchUserIDsResponse\x127\n" +
	"\fuser_results\x18\x01 \x03(\v2\x14.search.UserIDResultR\vuserResults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"s\n" +
	"\x17SearchThreadIDsResponse\x12=\n" +
	"\x0ethread_results\x18\x01 \x03(\v2\x16.search.ThreadIDResultR\rthreadResults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"2\n" +
	"\x1aGetTrendingHashtagsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"9\n" +
	"\x1bGetTrendingHashtagsResponse\x12\x1a\n" +
	"\bhashtags\x18\x01 \x03(\tR\bhashtags2\xbc\x02\n" +
	"\rSearchService\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.search.HealthResponse\x12C\n" +
	"\vSearchUsers\x12\x15.search.SearchRequest\x1a\x1d.search.SearchUserIDsResponse\x12G\n" +
	"\rSearchThreads\x12\x15.search.SearchRequest\x1a\x1f.search.SearchThreadIDsResponse\x12^\n" +
	"\x13GetTrendingHashtags\x12\".search.GetTrendingHashtagsRequest\x1a#.search.GetTrendingHashtagsResponseBSZQgithub.com/Acad600-TPA/WEB-MJ-242/backend/search-service/genproto/search;searchpbb\x06proto3"

var (
	file_proto_search_proto_rawDescOnce sync.Once
	file_proto_search_proto_rawDescData []byte
)

func file_proto_search_proto_rawDescGZIP() []byte {
	file_proto_search_proto_rawDescOnce.Do(func() {
		file_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)))
	})
	return file_proto_search_proto_rawDescData
}

var file_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_proto_search_proto_goTypes = []any{
	(*HealthResponse)(nil),              // 0: search.HealthResponse
	(*SearchRequest)(nil),               // 1: search.SearchRequest
	(*UserIDResult)(nil),                // 2: search.UserIDResult
	(*ThreadIDResult)(nil),              // 3: search.ThreadIDResult
	(*SearchUserIDsResponse)(nil),       // 4: search.SearchUserIDsResponse
	(*SearchThreadIDsResponse)(nil),     // 5: search.SearchThreadIDsResponse
	(*GetTrendingHashtagsRequest)(nil),  // 6: search.GetTrendingHashtagsRequest
	(*GetTrendingHashtagsResponse)(nil), // 7: search.GetTrendingHashtagsResponse
	(*emptypb.Empty)(nil),               // 8: google.protobuf.Empty
}
var file_proto_search_proto_depIdxs = []int32{
	2, // 0: search.SearchUserIDsResponse.user_results:type_name -> search.UserIDResult
	3, // 1: search.SearchThreadIDsResponse.thread_results:type_name -> search.ThreadIDResult
	8, // 2: search.SearchService.HealthCheck:input_type -> google.protobuf.Empty
	1, // 3: search.SearchService.SearchUsers:input_type -> search.SearchRequest
	1, // 4: search.SearchService.SearchThreads:input_type -> search.SearchRequest
	6, // 5: search.SearchService.GetTrendingHashtags:input_type -> search.GetTrendingHashtagsRequest
	0, // 6: search.SearchService.HealthCheck:output_type -> search.HealthResponse
	4, // 7: search.SearchService.SearchUsers:output_type -> search.SearchUserIDsResponse
	5, // 8: search.SearchService.SearchThreads:output_type -> search.SearchThreadIDsResponse
	7, // 9: search.SearchService.GetTrendingHashtags:output_type -> search.GetTrendingHashtagsResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_search_proto_init() }
func file_proto_search_proto_init() {
	if File_proto_search_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_proto_goTypes,
		DependencyIndexes: file_proto_search_proto_depIdxs,
		MessageInfos:      file_proto_search_proto_msgTypes,
	}.Build()
	File_proto_search_proto = out.File
	file_proto_search_proto_goTypes = nil
	file_proto_search_proto_depIdxs = nil
}
