// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/search.proto

package searchpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Query         string                 `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_proto_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type UserIDResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserIDResult) Reset() {
	*x = UserIDResult{}
	mi := &file_proto_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserIDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserIDResult) ProtoMessage() {}

func (x *UserIDResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserIDResult.ProtoReflect.Descriptor instead.
func (*UserIDResult) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{2}
}

func (x *UserIDResult) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ThreadIDResult struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ContentSnippet string                 `protobuf:"bytes,2,opt,name=content_snippet,json=contentSnippet,proto3" json:"content_snippet,omitempty"`
	UserId         uint32                 `protobuf:"varint,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ThreadIDResult) Reset() {
	*x = ThreadIDResult{}
	mi := &file_proto_search_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadIDResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadIDResult) ProtoMessage() {}

func (x *ThreadIDResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadIDResult.ProtoReflect.Descriptor instead.
func (*ThreadIDResult) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{3}
}

func (x *ThreadIDResult) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ThreadIDResult) GetContentSnippet() string {
	if x != nil {
		return x.ContentSnippet
	}
	return ""
}

func (x *ThreadIDResult) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type SearchUserIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserResults   []*UserIDResult        `protobuf:"bytes,1,rep,name=user_results,json=userResults,proto3" json:"user_results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUserIDsResponse) Reset() {
	*x = SearchUserIDsResponse{}
	mi := &file_proto_search_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUserIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUserIDsResponse) ProtoMessage() {}

func (x *SearchUserIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUserIDsResponse.ProtoReflect.Descriptor instead.
func (*SearchUserIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{4}
}

func (x *SearchUserIDsResponse) GetUserResults() []*UserIDResult {
	if x != nil {
		return x.UserResults
	}
	return nil
}

func (x *SearchUserIDsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type SearchThreadIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadResults []*ThreadIDResult      `protobuf:"bytes,1,rep,name=thread_results,json=threadResults,proto3" json:"thread_results,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchThreadIDsResponse) Reset() {
	*x = SearchThreadIDsResponse{}
	mi := &file_proto_search_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchThreadIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchThreadIDsResponse) ProtoMessage() {}

func (x *SearchThreadIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchThreadIDsResponse.ProtoReflect.Descriptor instead.
func (*SearchThreadIDsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{5}
}

func (x *SearchThreadIDsResponse) GetThreadResults() []*ThreadIDResult {
	if x != nil {
		return x.ThreadResults
	}
	return nil
}

func (x *SearchThreadIDsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type TrendingHashtag struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tag           string                 `protobuf:"bytes,1,opt,name=tag,proto3" json:"tag,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrendingHashtag) Reset() {
	*x = TrendingHashtag{}
	mi := &file_proto_search_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrendingHashtag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrendingHashtag) ProtoMessage() {}

func (x *TrendingHashtag) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrendingHashtag.ProtoReflect.Descriptor instead.
func (*TrendingHashtag) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{6}
}

func (x *TrendingHashtag) GetTag() string {
	if x != nil {
		return x.Tag
	}
	return ""
}

func (x *TrendingHashtag) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type GetTrendingHashtagsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingHashtagsRequest) Reset() {
	*x = GetTrendingHashtagsRequest{}
	mi := &file_proto_search_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingHashtagsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingHashtagsRequest) ProtoMessage() {}

func (x *GetTrendingHashtagsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingHashtagsRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingHashtagsRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{7}
}

func (x *GetTrendingHashtagsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetTrendingHashtagsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TrendingHashtags []*TrendingHashtag     `protobuf:"bytes,1,rep,name=trending_hashtags,json=trendingHashtags,proto3" json:"trending_hashtags,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetTrendingHashtagsResponse) Reset() {
	*x = GetTrendingHashtagsResponse{}
	mi := &file_proto_search_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingHashtagsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingHashtagsResponse) ProtoMessage() {}

func (x *GetTrendingHashtagsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingHashtagsResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingHashtagsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{8}
}

func (x *GetTrendingHashtagsResponse) GetTrendingHashtags() []*TrendingHashtag {
	if x != nil {
		return x.TrendingHashtags
	}
	return nil
}

type IncrementHashtagCountsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hashtags      []string               `protobuf:"bytes,1,rep,name=hashtags,proto3" json:"hashtags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementHashtagCountsRequest) Reset() {
	*x = IncrementHashtagCountsRequest{}
	mi := &file_proto_search_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementHashtagCountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementHashtagCountsRequest) ProtoMessage() {}

func (x *IncrementHashtagCountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementHashtagCountsRequest.ProtoReflect.Descriptor instead.
func (*IncrementHashtagCountsRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{9}
}

func (x *IncrementHashtagCountsRequest) GetHashtags() []string {
	if x != nil {
		return x.Hashtags
	}
	return nil
}

type IncrementHashtagCountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IncrementHashtagCountsResponse) Reset() {
	*x = IncrementHashtagCountsResponse{}
	mi := &file_proto_search_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncrementHashtagCountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncrementHashtagCountsResponse) ProtoMessage() {}

func (x *IncrementHashtagCountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncrementHashtagCountsResponse.ProtoReflect.Descriptor instead.
func (*IncrementHashtagCountsResponse) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{10}
}

func (x *IncrementHashtagCountsResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetTopUsersToFollowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	ExcludeUserId *uint32                `protobuf:"varint,2,opt,name=exclude_user_id,json=excludeUserId,proto3,oneof" json:"exclude_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTopUsersToFollowRequest) Reset() {
	*x = GetTopUsersToFollowRequest{}
	mi := &file_proto_search_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTopUsersToFollowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTopUsersToFollowRequest) ProtoMessage() {}

func (x *GetTopUsersToFollowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_search_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTopUsersToFollowRequest.ProtoReflect.Descriptor instead.
func (*GetTopUsersToFollowRequest) Descriptor() ([]byte, []int) {
	return file_proto_search_proto_rawDescGZIP(), []int{11}
}

func (x *GetTopUsersToFollowRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetTopUsersToFollowRequest) GetExcludeUserId() uint32 {
	if x != nil && x.ExcludeUserId != nil {
		return *x.ExcludeUserId
	}
	return 0
}

var File_proto_search_proto protoreflect.FileDescriptor

const file_proto_search_proto_rawDesc = "" +
	"\n" +
	"\x12proto/search.proto\x12\x06search\x1a\x1bgoogle/protobuf/empty.proto\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"O\n" +
	"\rSearchRequest\x12\x14\n" +
	"\x05query\x18\x01 \x01(\tR\x05query\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"\x1e\n" +
	"\fUserIDResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\"b\n" +
	"\x0eThreadIDResult\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12'\n" +
	"\x0fcontent_snippet\x18\x02 \x01(\tR\x0econtentSnippet\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\rR\x06userId\"k\n" +
	"\x15SearchUserIDsResponse\x127\n" +
	"\fuser_results\x18\x01 \x03(\v2\x14.search.UserIDResultR\vuserResults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"s\n" +
	"\x17SearchThreadIDsResponse\x12=\n" +
	"\x0ethread_results\x18\x01 \x03(\v2\x16.search.ThreadIDResultR\rthreadResults\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"9\n" +
	"\x0fTrendingHashtag\x12\x10\n" +
	"\x03tag\x18\x01 \x01(\tR\x03tag\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"2\n" +
	"\x1aGetTrendingHashtagsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"c\n" +
	"\x1bGetTrendingHashtagsResponse\x12D\n" +
	"\x11trending_hashtags\x18\x01 \x03(\v2\x17.search.TrendingHashtagR\x10trendingHashtags\";\n" +
	"\x1dIncrementHashtagCountsRequest\x12\x1a\n" +
	"\bhashtags\x18\x01 \x03(\tR\bhashtags\":\n" +
	"\x1eIncrementHashtagCountsResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"s\n" +
	"\x1aGetTopUsersToFollowRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12+\n" +
	"\x0fexclude_user_id\x18\x02 \x01(\rH\x00R\rexcludeUserId\x88\x01\x01B\x12\n" +
	"\x10_exclude_user_id2\xff\x03\n" +
	"\rSearchService\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.search.HealthResponse\x12C\n" +
	"\vSearchUsers\x12\x15.search.SearchRequest\x1a\x1d.search.SearchUserIDsResponse\x12G\n" +
	"\rSearchThreads\x12\x15.search.SearchRequest\x1a\x1f.search.SearchThreadIDsResponse\x12^\n" +
	"\x13GetTrendingHashtags\x12\".search.GetTrendingHashtagsRequest\x1a#.search.GetTrendingHashtagsResponse\x12g\n" +
	"\x16IncrementHashtagCounts\x12%.search.IncrementHashtagCountsRequest\x1a&.search.IncrementHashtagCountsResponse\x12X\n" +
	"\x13GetTopUsersToFollow\x12\".search.GetTopUsersToFollowRequest\x1a\x1d.search.SearchUserIDsResponseBSZQgithub.com/Acad600-TPA/WEB-MJ-242/backend/search-service/genproto/search;searchpbb\x06proto3"

var (
	file_proto_search_proto_rawDescOnce sync.Once
	file_proto_search_proto_rawDescData []byte
)

func file_proto_search_proto_rawDescGZIP() []byte {
	file_proto_search_proto_rawDescOnce.Do(func() {
		file_proto_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)))
	})
	return file_proto_search_proto_rawDescData
}

var file_proto_search_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_proto_search_proto_goTypes = []any{
	(*HealthResponse)(nil),                 // 0: search.HealthResponse
	(*SearchRequest)(nil),                  // 1: search.SearchRequest
	(*UserIDResult)(nil),                   // 2: search.UserIDResult
	(*ThreadIDResult)(nil),                 // 3: search.ThreadIDResult
	(*SearchUserIDsResponse)(nil),          // 4: search.SearchUserIDsResponse
	(*SearchThreadIDsResponse)(nil),        // 5: search.SearchThreadIDsResponse
	(*TrendingHashtag)(nil),                // 6: search.TrendingHashtag
	(*GetTrendingHashtagsRequest)(nil),     // 7: search.GetTrendingHashtagsRequest
	(*GetTrendingHashtagsResponse)(nil),    // 8: search.GetTrendingHashtagsResponse
	(*IncrementHashtagCountsRequest)(nil),  // 9: search.IncrementHashtagCountsRequest
	(*IncrementHashtagCountsResponse)(nil), // 10: search.IncrementHashtagCountsResponse
	(*GetTopUsersToFollowRequest)(nil),     // 11: search.GetTopUsersToFollowRequest
	(*emptypb.Empty)(nil),                  // 12: google.protobuf.Empty
}
var file_proto_search_proto_depIdxs = []int32{
	2,  // 0: search.SearchUserIDsResponse.user_results:type_name -> search.UserIDResult
	3,  // 1: search.SearchThreadIDsResponse.thread_results:type_name -> search.ThreadIDResult
	6,  // 2: search.GetTrendingHashtagsResponse.trending_hashtags:type_name -> search.TrendingHashtag
	12, // 3: search.SearchService.HealthCheck:input_type -> google.protobuf.Empty
	1,  // 4: search.SearchService.SearchUsers:input_type -> search.SearchRequest
	1,  // 5: search.SearchService.SearchThreads:input_type -> search.SearchRequest
	7,  // 6: search.SearchService.GetTrendingHashtags:input_type -> search.GetTrendingHashtagsRequest
	9,  // 7: search.SearchService.IncrementHashtagCounts:input_type -> search.IncrementHashtagCountsRequest
	11, // 8: search.SearchService.GetTopUsersToFollow:input_type -> search.GetTopUsersToFollowRequest
	0,  // 9: search.SearchService.HealthCheck:output_type -> search.HealthResponse
	4,  // 10: search.SearchService.SearchUsers:output_type -> search.SearchUserIDsResponse
	5,  // 11: search.SearchService.SearchThreads:output_type -> search.SearchThreadIDsResponse
	8,  // 12: search.SearchService.GetTrendingHashtags:output_type -> search.GetTrendingHashtagsResponse
	10, // 13: search.SearchService.IncrementHashtagCounts:output_type -> search.IncrementHashtagCountsResponse
	4,  // 14: search.SearchService.GetTopUsersToFollow:output_type -> search.SearchUserIDsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_proto_search_proto_init() }
func file_proto_search_proto_init() {
	if File_proto_search_proto != nil {
		return
	}
	file_proto_search_proto_msgTypes[11].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_search_proto_rawDesc), len(file_proto_search_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_search_proto_goTypes,
		DependencyIndexes: file_proto_search_proto_depIdxs,
		MessageInfos:      file_proto_search_proto_msgTypes,
	}.Build()
	File_proto_search_proto = out.File
	file_proto_search_proto_goTypes = nil
	file_proto_search_proto_depIdxs = nil
}
