// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/thread.proto

package genproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReplyRestriction int32

const (
	ReplyRestriction_REPLY_RESTRICTION_UNSPECIFIED ReplyRestriction = 0
	ReplyRestriction_EVERYONE                      ReplyRestriction = 1
	ReplyRestriction_FOLLOWING                     ReplyRestriction = 2
	ReplyRestriction_VERIFIED                      ReplyRestriction = 3
)

// Enum value maps for ReplyRestriction.
var (
	ReplyRestriction_name = map[int32]string{
		0: "REPLY_RESTRICTION_UNSPECIFIED",
		1: "EVERYONE",
		2: "FOLLOWING",
		3: "VERIFIED",
	}
	ReplyRestriction_value = map[string]int32{
		"REPLY_RESTRICTION_UNSPECIFIED": 0,
		"EVERYONE":                      1,
		"FOLLOWING":                     2,
		"VERIFIED":                      3,
	}
)

func (x ReplyRestriction) Enum() *ReplyRestriction {
	p := new(ReplyRestriction)
	*p = x
	return p
}

func (x ReplyRestriction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReplyRestriction) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_thread_proto_enumTypes[0].Descriptor()
}

func (ReplyRestriction) Type() protoreflect.EnumType {
	return &file_proto_thread_proto_enumTypes[0]
}

func (x ReplyRestriction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReplyRestriction.Descriptor instead.
func (ReplyRestriction) EnumDescriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{0}
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_proto_thread_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{0}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Thread struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Id                        uint32                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId                    uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content                   string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	ParentThreadId            *uint32                `protobuf:"varint,4,opt,name=parent_thread_id,json=parentThreadId,proto3,oneof" json:"parent_thread_id,omitempty"`
	ReplyRestriction          ReplyRestriction       `protobuf:"varint,5,opt,name=reply_restriction,json=replyRestriction,proto3,enum=thread.ReplyRestriction" json:"reply_restriction,omitempty"`
	ScheduledAt               *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	PostedAt                  *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=posted_at,json=postedAt,proto3" json:"posted_at,omitempty"`
	CommunityId               *uint32                `protobuf:"varint,8,opt,name=community_id,json=communityId,proto3,oneof" json:"community_id,omitempty"`
	IsAdvertisement           bool                   `protobuf:"varint,9,opt,name=is_advertisement,json=isAdvertisement,proto3" json:"is_advertisement,omitempty"`
	MediaIds                  []uint32               `protobuf:"varint,10,rep,packed,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`
	CreatedAt                 *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	LikeCount                 int32                  `protobuf:"varint,12,opt,name=like_count,json=likeCount,proto3" json:"like_count,omitempty"`
	ReplyCount                int32                  `protobuf:"varint,13,opt,name=reply_count,json=replyCount,proto3" json:"reply_count,omitempty"`
	RepostCount               int32                  `protobuf:"varint,14,opt,name=repost_count,json=repostCount,proto3" json:"repost_count,omitempty"`
	BookmarkCount             int32                  `protobuf:"varint,15,opt,name=bookmark_count,json=bookmarkCount,proto3" json:"bookmark_count,omitempty"`
	IsLikedByCurrentUser      bool                   `protobuf:"varint,16,opt,name=is_liked_by_current_user,json=isLikedByCurrentUser,proto3" json:"is_liked_by_current_user,omitempty"`
	IsBookmarkedByCurrentUser bool                   `protobuf:"varint,17,opt,name=is_bookmarked_by_current_user,json=isBookmarkedByCurrentUser,proto3" json:"is_bookmarked_by_current_user,omitempty"`
	Categories                []string               `protobuf:"bytes,18,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Thread) Reset() {
	*x = Thread{}
	mi := &file_proto_thread_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Thread) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Thread) ProtoMessage() {}

func (x *Thread) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Thread.ProtoReflect.Descriptor instead.
func (*Thread) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{1}
}

func (x *Thread) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Thread) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *Thread) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Thread) GetParentThreadId() uint32 {
	if x != nil && x.ParentThreadId != nil {
		return *x.ParentThreadId
	}
	return 0
}

func (x *Thread) GetReplyRestriction() ReplyRestriction {
	if x != nil {
		return x.ReplyRestriction
	}
	return ReplyRestriction_REPLY_RESTRICTION_UNSPECIFIED
}

func (x *Thread) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *Thread) GetPostedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PostedAt
	}
	return nil
}

func (x *Thread) GetCommunityId() uint32 {
	if x != nil && x.CommunityId != nil {
		return *x.CommunityId
	}
	return 0
}

func (x *Thread) GetIsAdvertisement() bool {
	if x != nil {
		return x.IsAdvertisement
	}
	return false
}

func (x *Thread) GetMediaIds() []uint32 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

func (x *Thread) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Thread) GetLikeCount() int32 {
	if x != nil {
		return x.LikeCount
	}
	return 0
}

func (x *Thread) GetReplyCount() int32 {
	if x != nil {
		return x.ReplyCount
	}
	return 0
}

func (x *Thread) GetRepostCount() int32 {
	if x != nil {
		return x.RepostCount
	}
	return 0
}

func (x *Thread) GetBookmarkCount() int32 {
	if x != nil {
		return x.BookmarkCount
	}
	return 0
}

func (x *Thread) GetIsLikedByCurrentUser() bool {
	if x != nil {
		return x.IsLikedByCurrentUser
	}
	return false
}

func (x *Thread) GetIsBookmarkedByCurrentUser() bool {
	if x != nil {
		return x.IsBookmarkedByCurrentUser
	}
	return false
}

func (x *Thread) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type CreateThreadRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	UserId           uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Content          string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ParentThreadId   *uint32                `protobuf:"varint,3,opt,name=parent_thread_id,json=parentThreadId,proto3,oneof" json:"parent_thread_id,omitempty"`
	ReplyRestriction ReplyRestriction       `protobuf:"varint,4,opt,name=reply_restriction,json=replyRestriction,proto3,enum=thread.ReplyRestriction" json:"reply_restriction,omitempty"`
	ScheduledAt      *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	CommunityId      *uint32                `protobuf:"varint,6,opt,name=community_id,json=communityId,proto3,oneof" json:"community_id,omitempty"`
	MediaIds         []uint32               `protobuf:"varint,7,rep,packed,name=media_ids,json=mediaIds,proto3" json:"media_ids,omitempty"`
	Categories       []string               `protobuf:"bytes,8,rep,name=categories,proto3" json:"categories,omitempty"` // is_advertisement
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateThreadRequest) Reset() {
	*x = CreateThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateThreadRequest) ProtoMessage() {}

func (x *CreateThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateThreadRequest.ProtoReflect.Descriptor instead.
func (*CreateThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{2}
}

func (x *CreateThreadRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *CreateThreadRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *CreateThreadRequest) GetParentThreadId() uint32 {
	if x != nil && x.ParentThreadId != nil {
		return *x.ParentThreadId
	}
	return 0
}

func (x *CreateThreadRequest) GetReplyRestriction() ReplyRestriction {
	if x != nil {
		return x.ReplyRestriction
	}
	return ReplyRestriction_REPLY_RESTRICTION_UNSPECIFIED
}

func (x *CreateThreadRequest) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

func (x *CreateThreadRequest) GetCommunityId() uint32 {
	if x != nil && x.CommunityId != nil {
		return *x.CommunityId
	}
	return 0
}

func (x *CreateThreadRequest) GetMediaIds() []uint32 {
	if x != nil {
		return x.MediaIds
	}
	return nil
}

func (x *CreateThreadRequest) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

type GetThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      uint32                 `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	CurrentUserId *uint32                `protobuf:"varint,2,opt,name=current_user_id,json=currentUserId,proto3,oneof" json:"current_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetThreadRequest) Reset() {
	*x = GetThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThreadRequest) ProtoMessage() {}

func (x *GetThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThreadRequest.ProtoReflect.Descriptor instead.
func (*GetThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{3}
}

func (x *GetThreadRequest) GetThreadId() uint32 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *GetThreadRequest) GetCurrentUserId() uint32 {
	if x != nil && x.CurrentUserId != nil {
		return *x.CurrentUserId
	}
	return 0
}

type DeleteThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      uint32                 `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteThreadRequest) Reset() {
	*x = DeleteThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteThreadRequest) ProtoMessage() {}

func (x *DeleteThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteThreadRequest.ProtoReflect.Descriptor instead.
func (*DeleteThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteThreadRequest) GetThreadId() uint32 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *DeleteThreadRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type InteractThreadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ThreadId      uint32                 `protobuf:"varint,1,opt,name=thread_id,json=threadId,proto3" json:"thread_id,omitempty"`
	UserId        uint32                 `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InteractThreadRequest) Reset() {
	*x = InteractThreadRequest{}
	mi := &file_proto_thread_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InteractThreadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InteractThreadRequest) ProtoMessage() {}

func (x *InteractThreadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InteractThreadRequest.ProtoReflect.Descriptor instead.
func (*InteractThreadRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{5}
}

func (x *InteractThreadRequest) GetThreadId() uint32 {
	if x != nil {
		return x.ThreadId
	}
	return 0
}

func (x *InteractThreadRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type GetFeedThreadsRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	CurrentUserId      *uint32                `protobuf:"varint,1,opt,name=current_user_id,json=currentUserId,proto3,oneof" json:"current_user_id,omitempty"`
	Page               int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	Limit              int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	FeedType           string                 `protobuf:"bytes,4,opt,name=feed_type,json=feedType,proto3" json:"feed_type,omitempty"`                                           // "foryou", "following"
	ExcludeUserIds     []uint32               `protobuf:"varint,5,rep,packed,name=exclude_user_ids,json=excludeUserIds,proto3" json:"exclude_user_ids,omitempty"`               // for blocked or blocking
	IncludeOnlyUserIds []uint32               `protobuf:"varint,6,rep,packed,name=include_only_user_ids,json=includeOnlyUserIds,proto3" json:"include_only_user_ids,omitempty"` // for "following"
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GetFeedThreadsRequest) Reset() {
	*x = GetFeedThreadsRequest{}
	mi := &file_proto_thread_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedThreadsRequest) ProtoMessage() {}

func (x *GetFeedThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedThreadsRequest.ProtoReflect.Descriptor instead.
func (*GetFeedThreadsRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{6}
}

func (x *GetFeedThreadsRequest) GetCurrentUserId() uint32 {
	if x != nil && x.CurrentUserId != nil {
		return *x.CurrentUserId
	}
	return 0
}

func (x *GetFeedThreadsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetFeedThreadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetFeedThreadsRequest) GetFeedType() string {
	if x != nil {
		return x.FeedType
	}
	return ""
}

func (x *GetFeedThreadsRequest) GetExcludeUserIds() []uint32 {
	if x != nil {
		return x.ExcludeUserIds
	}
	return nil
}

func (x *GetFeedThreadsRequest) GetIncludeOnlyUserIds() []uint32 {
	if x != nil {
		return x.IncludeOnlyUserIds
	}
	return nil
}

type GetFeedThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*Thread              `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedThreadsResponse) Reset() {
	*x = GetFeedThreadsResponse{}
	mi := &file_proto_thread_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedThreadsResponse) ProtoMessage() {}

func (x *GetFeedThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedThreadsResponse.ProtoReflect.Descriptor instead.
func (*GetFeedThreadsResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{7}
}

func (x *GetFeedThreadsResponse) GetThreads() []*Thread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *GetFeedThreadsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetUserThreadsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TargetUserId    uint32                 `protobuf:"varint,1,opt,name=target_user_id,json=targetUserId,proto3" json:"target_user_id,omitempty"`
	RequesterUserId *uint32                `protobuf:"varint,2,opt,name=requester_user_id,json=requesterUserId,proto3,oneof" json:"requester_user_id,omitempty"`
	ThreadType      string                 `protobuf:"bytes,3,opt,name=thread_type,json=threadType,proto3" json:"thread_type,omitempty"` // "posts", "replies", "likes", "media"
	Page            int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit           int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	ExcludeUserIds  []uint32               `protobuf:"varint,6,rep,packed,name=exclude_user_ids,json=excludeUserIds,proto3" json:"exclude_user_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUserThreadsRequest) Reset() {
	*x = GetUserThreadsRequest{}
	mi := &file_proto_thread_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserThreadsRequest) ProtoMessage() {}

func (x *GetUserThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserThreadsRequest.ProtoReflect.Descriptor instead.
func (*GetUserThreadsRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{8}
}

func (x *GetUserThreadsRequest) GetTargetUserId() uint32 {
	if x != nil {
		return x.TargetUserId
	}
	return 0
}

func (x *GetUserThreadsRequest) GetRequesterUserId() uint32 {
	if x != nil && x.RequesterUserId != nil {
		return *x.RequesterUserId
	}
	return 0
}

func (x *GetUserThreadsRequest) GetThreadType() string {
	if x != nil {
		return x.ThreadType
	}
	return ""
}

func (x *GetUserThreadsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetUserThreadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetUserThreadsRequest) GetExcludeUserIds() []uint32 {
	if x != nil {
		return x.ExcludeUserIds
	}
	return nil
}

type GetUserThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*Thread              `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserThreadsResponse) Reset() {
	*x = GetUserThreadsResponse{}
	mi := &file_proto_thread_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserThreadsResponse) ProtoMessage() {}

func (x *GetUserThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserThreadsResponse.ProtoReflect.Descriptor instead.
func (*GetUserThreadsResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserThreadsResponse) GetThreads() []*Thread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *GetUserThreadsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetCommunityThreadsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CommunityId     uint32                 `protobuf:"varint,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	RequesterUserId *uint32                `protobuf:"varint,2,opt,name=requester_user_id,json=requesterUserId,proto3,oneof" json:"requester_user_id,omitempty"`
	SortType        string                 `protobuf:"bytes,3,opt,name=sort_type,json=sortType,proto3" json:"sort_type,omitempty"` // "latest", "top" (for posts within community)
	Page            int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit           int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	ExcludeUserIds  []uint32               `protobuf:"varint,6,rep,packed,name=exclude_user_ids,json=excludeUserIds,proto3" json:"exclude_user_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetCommunityThreadsRequest) Reset() {
	*x = GetCommunityThreadsRequest{}
	mi := &file_proto_thread_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityThreadsRequest) ProtoMessage() {}

func (x *GetCommunityThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityThreadsRequest.ProtoReflect.Descriptor instead.
func (*GetCommunityThreadsRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{10}
}

func (x *GetCommunityThreadsRequest) GetCommunityId() uint32 {
	if x != nil {
		return x.CommunityId
	}
	return 0
}

func (x *GetCommunityThreadsRequest) GetRequesterUserId() uint32 {
	if x != nil && x.RequesterUserId != nil {
		return *x.RequesterUserId
	}
	return 0
}

func (x *GetCommunityThreadsRequest) GetSortType() string {
	if x != nil {
		return x.SortType
	}
	return ""
}

func (x *GetCommunityThreadsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetCommunityThreadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetCommunityThreadsRequest) GetExcludeUserIds() []uint32 {
	if x != nil {
		return x.ExcludeUserIds
	}
	return nil
}

type GetCommunityThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*Thread              `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityThreadsResponse) Reset() {
	*x = GetCommunityThreadsResponse{}
	mi := &file_proto_thread_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityThreadsResponse) ProtoMessage() {}

func (x *GetCommunityThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityThreadsResponse.ProtoReflect.Descriptor instead.
func (*GetCommunityThreadsResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{11}
}

func (x *GetCommunityThreadsResponse) GetThreads() []*Thread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *GetCommunityThreadsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetBookmarkedThreadsRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          uint32                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	RequesterUserId *uint32                `protobuf:"varint,2,opt,name=requester_user_id,json=requesterUserId,proto3,oneof" json:"requester_user_id,omitempty"`
	Page            int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Limit           int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetBookmarkedThreadsRequest) Reset() {
	*x = GetBookmarkedThreadsRequest{}
	mi := &file_proto_thread_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookmarkedThreadsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookmarkedThreadsRequest) ProtoMessage() {}

func (x *GetBookmarkedThreadsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookmarkedThreadsRequest.ProtoReflect.Descriptor instead.
func (*GetBookmarkedThreadsRequest) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{12}
}

func (x *GetBookmarkedThreadsRequest) GetUserId() uint32 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *GetBookmarkedThreadsRequest) GetRequesterUserId() uint32 {
	if x != nil && x.RequesterUserId != nil {
		return *x.RequesterUserId
	}
	return 0
}

func (x *GetBookmarkedThreadsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetBookmarkedThreadsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetBookmarkedThreadsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Threads       []*Thread              `protobuf:"bytes,1,rep,name=threads,proto3" json:"threads,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBookmarkedThreadsResponse) Reset() {
	*x = GetBookmarkedThreadsResponse{}
	mi := &file_proto_thread_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBookmarkedThreadsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookmarkedThreadsResponse) ProtoMessage() {}

func (x *GetBookmarkedThreadsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_thread_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookmarkedThreadsResponse.ProtoReflect.Descriptor instead.
func (*GetBookmarkedThreadsResponse) Descriptor() ([]byte, []int) {
	return file_proto_thread_proto_rawDescGZIP(), []int{13}
}

func (x *GetBookmarkedThreadsResponse) GetThreads() []*Thread {
	if x != nil {
		return x.Threads
	}
	return nil
}

func (x *GetBookmarkedThreadsResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_proto_thread_proto protoreflect.FileDescriptor

const file_proto_thread_proto_rawDesc = "" +
	"\n" +
	"\x12proto/thread.proto\x12\x06thread\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xae\x06\n" +
	"\x06Thread\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\rR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12-\n" +
	"\x10parent_thread_id\x18\x04 \x01(\rH\x00R\x0eparentThreadId\x88\x01\x01\x12E\n" +
	"\x11reply_restriction\x18\x05 \x01(\x0e2\x18.thread.ReplyRestrictionR\x10replyRestriction\x12=\n" +
	"\fscheduled_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x127\n" +
	"\tposted_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\bpostedAt\x12&\n" +
	"\fcommunity_id\x18\b \x01(\rH\x01R\vcommunityId\x88\x01\x01\x12)\n" +
	"\x10is_advertisement\x18\t \x01(\bR\x0fisAdvertisement\x12\x1b\n" +
	"\tmedia_ids\x18\n" +
	" \x03(\rR\bmediaIds\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"like_count\x18\f \x01(\x05R\tlikeCount\x12\x1f\n" +
	"\vreply_count\x18\r \x01(\x05R\n" +
	"replyCount\x12!\n" +
	"\frepost_count\x18\x0e \x01(\x05R\vrepostCount\x12%\n" +
	"\x0ebookmark_count\x18\x0f \x01(\x05R\rbookmarkCount\x126\n" +
	"\x18is_liked_by_current_user\x18\x10 \x01(\bR\x14isLikedByCurrentUser\x12@\n" +
	"\x1dis_bookmarked_by_current_user\x18\x11 \x01(\bR\x19isBookmarkedByCurrentUser\x12\x1e\n" +
	"\n" +
	"categories\x18\x12 \x03(\tR\n" +
	"categoriesB\x13\n" +
	"\x11_parent_thread_idB\x0f\n" +
	"\r_community_id\"\x88\x03\n" +
	"\x13CreateThreadRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12-\n" +
	"\x10parent_thread_id\x18\x03 \x01(\rH\x00R\x0eparentThreadId\x88\x01\x01\x12E\n" +
	"\x11reply_restriction\x18\x04 \x01(\x0e2\x18.thread.ReplyRestrictionR\x10replyRestriction\x12=\n" +
	"\fscheduled_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\x12&\n" +
	"\fcommunity_id\x18\x06 \x01(\rH\x01R\vcommunityId\x88\x01\x01\x12\x1b\n" +
	"\tmedia_ids\x18\a \x03(\rR\bmediaIds\x12\x1e\n" +
	"\n" +
	"categories\x18\b \x03(\tR\n" +
	"categoriesB\x13\n" +
	"\x11_parent_thread_idB\x0f\n" +
	"\r_community_id\"p\n" +
	"\x10GetThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\rR\bthreadId\x12+\n" +
	"\x0fcurrent_user_id\x18\x02 \x01(\rH\x00R\rcurrentUserId\x88\x01\x01B\x12\n" +
	"\x10_current_user_id\"K\n" +
	"\x13DeleteThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\rR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"M\n" +
	"\x15InteractThreadRequest\x12\x1b\n" +
	"\tthread_id\x18\x01 \x01(\rR\bthreadId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\rR\x06userId\"\xfc\x01\n" +
	"\x15GetFeedThreadsRequest\x12+\n" +
	"\x0fcurrent_user_id\x18\x01 \x01(\rH\x00R\rcurrentUserId\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x1b\n" +
	"\tfeed_type\x18\x04 \x01(\tR\bfeedType\x12(\n" +
	"\x10exclude_user_ids\x18\x05 \x03(\rR\x0eexcludeUserIds\x121\n" +
	"\x15include_only_user_ids\x18\x06 \x03(\rR\x12includeOnlyUserIdsB\x12\n" +
	"\x10_current_user_id\"]\n" +
	"\x16GetFeedThreadsResponse\x12(\n" +
	"\athreads\x18\x01 \x03(\v2\x0e.thread.ThreadR\athreads\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xf9\x01\n" +
	"\x15GetUserThreadsRequest\x12$\n" +
	"\x0etarget_user_id\x18\x01 \x01(\rR\ftargetUserId\x12/\n" +
	"\x11requester_user_id\x18\x02 \x01(\rH\x00R\x0frequesterUserId\x88\x01\x01\x12\x1f\n" +
	"\vthread_type\x18\x03 \x01(\tR\n" +
	"threadType\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12(\n" +
	"\x10exclude_user_ids\x18\x06 \x03(\rR\x0eexcludeUserIdsB\x14\n" +
	"\x12_requester_user_id\"]\n" +
	"\x16GetUserThreadsResponse\x12(\n" +
	"\athreads\x18\x01 \x03(\v2\x0e.thread.ThreadR\athreads\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xf7\x01\n" +
	"\x1aGetCommunityThreadsRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\rR\vcommunityId\x12/\n" +
	"\x11requester_user_id\x18\x02 \x01(\rH\x00R\x0frequesterUserId\x88\x01\x01\x12\x1b\n" +
	"\tsort_type\x18\x03 \x01(\tR\bsortType\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12(\n" +
	"\x10exclude_user_ids\x18\x06 \x03(\rR\x0eexcludeUserIdsB\x14\n" +
	"\x12_requester_user_id\"b\n" +
	"\x1bGetCommunityThreadsResponse\x12(\n" +
	"\athreads\x18\x01 \x03(\v2\x0e.thread.ThreadR\athreads\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"\xa7\x01\n" +
	"\x1bGetBookmarkedThreadsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\rR\x06userId\x12/\n" +
	"\x11requester_user_id\x18\x02 \x01(\rH\x00R\x0frequesterUserId\x88\x01\x01\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\x14\n" +
	"\x12_requester_user_id\"c\n" +
	"\x1cGetBookmarkedThreadsResponse\x12(\n" +
	"\athreads\x18\x01 \x03(\v2\x0e.thread.ThreadR\athreads\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore*`\n" +
	"\x10ReplyRestriction\x12!\n" +
	"\x1dREPLY_RESTRICTION_UNSPECIFIED\x10\x00\x12\f\n" +
	"\bEVERYONE\x10\x01\x12\r\n" +
	"\tFOLLOWING\x10\x02\x12\f\n" +
	"\bVERIFIED\x10\x032\x8c\a\n" +
	"\rThreadService\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.thread.HealthResponse\x12;\n" +
	"\fCreateThread\x12\x1b.thread.CreateThreadRequest\x1a\x0e.thread.Thread\x125\n" +
	"\tGetThread\x12\x18.thread.GetThreadRequest\x1a\x0e.thread.Thread\x12C\n" +
	"\fDeleteThread\x12\x1b.thread.DeleteThreadRequest\x1a\x16.google.protobuf.Empty\x12C\n" +
	"\n" +
	"LikeThread\x12\x1d.thread.InteractThreadRequest\x1a\x16.google.protobuf.Empty\x12E\n" +
	"\fUnlikeThread\x12\x1d.thread.InteractThreadRequest\x1a\x16.google.protobuf.Empty\x12G\n" +
	"\x0eBookmarkThread\x12\x1d.thread.InteractThreadRequest\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\x10UnbookmarkThread\x12\x1d.thread.InteractThreadRequest\x1a\x16.google.protobuf.Empty\x12O\n" +
	"\x0eGetFeedThreads\x12\x1d.thread.GetFeedThreadsRequest\x1a\x1e.thread.GetFeedThreadsResponse\x12O\n" +
	"\x0eGetUserThreads\x12\x1d.thread.GetUserThreadsRequest\x1a\x1e.thread.GetUserThreadsResponse\x12a\n" +
	"\x14GetBookmarkedThreads\x12#.thread.GetBookmarkedThreadsRequest\x1a$.thread.GetBookmarkedThreadsResponse\x12^\n" +
	"\x13GetCommunityThreads\x12\".thread.GetCommunityThreadsRequest\x1a#.thread.GetCommunityThreadsResponseBCZAgithub.com/Acad600-TPA/WEB-MJ-242/backend/thread-service/genprotob\x06proto3"

var (
	file_proto_thread_proto_rawDescOnce sync.Once
	file_proto_thread_proto_rawDescData []byte
)

func file_proto_thread_proto_rawDescGZIP() []byte {
	file_proto_thread_proto_rawDescOnce.Do(func() {
		file_proto_thread_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_thread_proto_rawDesc), len(file_proto_thread_proto_rawDesc)))
	})
	return file_proto_thread_proto_rawDescData
}

var file_proto_thread_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_thread_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_thread_proto_goTypes = []any{
	(ReplyRestriction)(0),                // 0: thread.ReplyRestriction
	(*HealthResponse)(nil),               // 1: thread.HealthResponse
	(*Thread)(nil),                       // 2: thread.Thread
	(*CreateThreadRequest)(nil),          // 3: thread.CreateThreadRequest
	(*GetThreadRequest)(nil),             // 4: thread.GetThreadRequest
	(*DeleteThreadRequest)(nil),          // 5: thread.DeleteThreadRequest
	(*InteractThreadRequest)(nil),        // 6: thread.InteractThreadRequest
	(*GetFeedThreadsRequest)(nil),        // 7: thread.GetFeedThreadsRequest
	(*GetFeedThreadsResponse)(nil),       // 8: thread.GetFeedThreadsResponse
	(*GetUserThreadsRequest)(nil),        // 9: thread.GetUserThreadsRequest
	(*GetUserThreadsResponse)(nil),       // 10: thread.GetUserThreadsResponse
	(*GetCommunityThreadsRequest)(nil),   // 11: thread.GetCommunityThreadsRequest
	(*GetCommunityThreadsResponse)(nil),  // 12: thread.GetCommunityThreadsResponse
	(*GetBookmarkedThreadsRequest)(nil),  // 13: thread.GetBookmarkedThreadsRequest
	(*GetBookmarkedThreadsResponse)(nil), // 14: thread.GetBookmarkedThreadsResponse
	(*timestamppb.Timestamp)(nil),        // 15: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                // 16: google.protobuf.Empty
}
var file_proto_thread_proto_depIdxs = []int32{
	0,  // 0: thread.Thread.reply_restriction:type_name -> thread.ReplyRestriction
	15, // 1: thread.Thread.scheduled_at:type_name -> google.protobuf.Timestamp
	15, // 2: thread.Thread.posted_at:type_name -> google.protobuf.Timestamp
	15, // 3: thread.Thread.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: thread.CreateThreadRequest.reply_restriction:type_name -> thread.ReplyRestriction
	15, // 5: thread.CreateThreadRequest.scheduled_at:type_name -> google.protobuf.Timestamp
	2,  // 6: thread.GetFeedThreadsResponse.threads:type_name -> thread.Thread
	2,  // 7: thread.GetUserThreadsResponse.threads:type_name -> thread.Thread
	2,  // 8: thread.GetCommunityThreadsResponse.threads:type_name -> thread.Thread
	2,  // 9: thread.GetBookmarkedThreadsResponse.threads:type_name -> thread.Thread
	16, // 10: thread.ThreadService.HealthCheck:input_type -> google.protobuf.Empty
	3,  // 11: thread.ThreadService.CreateThread:input_type -> thread.CreateThreadRequest
	4,  // 12: thread.ThreadService.GetThread:input_type -> thread.GetThreadRequest
	5,  // 13: thread.ThreadService.DeleteThread:input_type -> thread.DeleteThreadRequest
	6,  // 14: thread.ThreadService.LikeThread:input_type -> thread.InteractThreadRequest
	6,  // 15: thread.ThreadService.UnlikeThread:input_type -> thread.InteractThreadRequest
	6,  // 16: thread.ThreadService.BookmarkThread:input_type -> thread.InteractThreadRequest
	6,  // 17: thread.ThreadService.UnbookmarkThread:input_type -> thread.InteractThreadRequest
	7,  // 18: thread.ThreadService.GetFeedThreads:input_type -> thread.GetFeedThreadsRequest
	9,  // 19: thread.ThreadService.GetUserThreads:input_type -> thread.GetUserThreadsRequest
	13, // 20: thread.ThreadService.GetBookmarkedThreads:input_type -> thread.GetBookmarkedThreadsRequest
	11, // 21: thread.ThreadService.GetCommunityThreads:input_type -> thread.GetCommunityThreadsRequest
	1,  // 22: thread.ThreadService.HealthCheck:output_type -> thread.HealthResponse
	2,  // 23: thread.ThreadService.CreateThread:output_type -> thread.Thread
	2,  // 24: thread.ThreadService.GetThread:output_type -> thread.Thread
	16, // 25: thread.ThreadService.DeleteThread:output_type -> google.protobuf.Empty
	16, // 26: thread.ThreadService.LikeThread:output_type -> google.protobuf.Empty
	16, // 27: thread.ThreadService.UnlikeThread:output_type -> google.protobuf.Empty
	16, // 28: thread.ThreadService.BookmarkThread:output_type -> google.protobuf.Empty
	16, // 29: thread.ThreadService.UnbookmarkThread:output_type -> google.protobuf.Empty
	8,  // 30: thread.ThreadService.GetFeedThreads:output_type -> thread.GetFeedThreadsResponse
	10, // 31: thread.ThreadService.GetUserThreads:output_type -> thread.GetUserThreadsResponse
	14, // 32: thread.ThreadService.GetBookmarkedThreads:output_type -> thread.GetBookmarkedThreadsResponse
	12, // 33: thread.ThreadService.GetCommunityThreads:output_type -> thread.GetCommunityThreadsResponse
	22, // [22:34] is the sub-list for method output_type
	10, // [10:22] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_proto_thread_proto_init() }
func file_proto_thread_proto_init() {
	if File_proto_thread_proto != nil {
		return
	}
	file_proto_thread_proto_msgTypes[1].OneofWrappers = []any{}
	file_proto_thread_proto_msgTypes[2].OneofWrappers = []any{}
	file_proto_thread_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_thread_proto_msgTypes[6].OneofWrappers = []any{}
	file_proto_thread_proto_msgTypes[8].OneofWrappers = []any{}
	file_proto_thread_proto_msgTypes[10].OneofWrappers = []any{}
	file_proto_thread_proto_msgTypes[12].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_thread_proto_rawDesc), len(file_proto_thread_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_thread_proto_goTypes,
		DependencyIndexes: file_proto_thread_proto_depIdxs,
		EnumInfos:         file_proto_thread_proto_enumTypes,
		MessageInfos:      file_proto_thread_proto_msgTypes,
	}.Build()
	File_proto_thread_proto = out.File
	file_proto_thread_proto_goTypes = nil
	file_proto_thread_proto_depIdxs = nil
}
